# PriceCheckTN MLOps Pipeline
# Data Version Control pipeline for reproducible workflows

stages:
  # Stage 1: Data Collection
  scrape:
    cmd: python scripts/run_scraping.py
    deps:
      - scripts/run_scraping.py
      - scraping/
      - config/base.py
    outs:
      - data/raw/mytek_latest.csv
      - data/raw/tunisianet_latest.csv
      - data/raw/ldlc_latest.csv

  # Stage 2: Data Processing
  consolidate:
    cmd: python scripts/consolidate.py
    deps:
      - data/raw/mytek_latest.csv
      - data/raw/tunisianet_latest.csv
      - data/raw/ldlc_latest.csv
      - scripts/consolidate.py
      - config/base.py
    outs:
      - data/final/products_unified.csv
      - data/final/products_unified.json
      - data/final/consolidation_report.txt
      - data/final/consolidation_stats.json

  # Stage 3: Product Matching
  match:
    cmd: python scripts/match_products.py
    deps:
      - data/final/products_unified.csv
      - scripts/match_products.py
      - config/base.py
    outs:
      - data/final/price_comparison.csv
      - data/final/price_comparison.json
      - data/final/unmatched_tn_products.csv
      - data/final/unmatched_fr_products.csv

  # Stage 4: Review Analysis
  analyze_reviews:
    cmd: python nlp/prediction.py
    deps:
      - data/final/products_unified.csv
      - nlp/prediction.py
      - nlp/
      - models/fake_review_detector_xgboost.pkl
      - config/base.py
    outs:
      - data/final/reviews_with_predictions.csv
      - data/final/reviews_with_predictions.json
      - data/final/fake_reviews_detected.csv

  # Stage 5: Metadata Generation
  generate_metadata:
    cmd: python scripts/generate_metadata.py
    deps:
      - data/final/products_unified.csv
      - data/final/reviews_with_predictions.csv
      - scripts/generate_metadata.py
      - config/base.py
    outs:
      - data/final/metadata/full_metadata.json
      - data/final/metadata/full_report.txt

  # Stage 6: BERT Model Training (Optional)
  train_bert:
    cmd: python scripts/train_bert.py --data data/final/reviews_with_features.csv --epochs 3 --batch-size 16
    deps:
      - data/final/reviews_with_features.csv
      - scripts/train_bert.py
      - nlp/training/bert_trainer.py
      - nlp/dataset.py
    outs:
      - models/saved_models/bert_fake_review/final_model/
    always_changed: true  # Always run this stage to allow retraining

  # Stage 7: MongoDB Export
  export_mongodb:
    cmd: python scripts/export_mongodb.py
    deps:
      - data/final/products_unified.csv
      - data/final/reviews_with_predictions.csv
      - data/final/metadata/
      - scripts/export_mongodb.py
      - config/base.py
    outs:
      - data/final/mongodb/
